export const exampleImportDish = [
  {
    weightSum: "330",
    caloriesSum: "242",
    proteinSum: "30",
    fatsSum: "5",
    carbsSum: "12",
    caloriesPerHundredGrams: "73",
    proteinsPerHundredGrams: "9",
    fatsPerHundredGrams: "2",
    carbsPerHundredGrams: "4",
    ingredientsList: "Cheese, Apple, Cocoa.",
    ingredientsArr: [
      {
        ingredientName: "Cheese",
        weight: 200,
        calories: 70,
        protein: 15,
        fats: 1,
        carbs: 0,
      },
      {
        ingredientName: "Apple",
        weight: 120,
        calories: 60,
        protein: 0,
        fats: 0,
        carbs: 10,
      },
      {
        ingredientName: "Cocoa",
        weight: 10,
        calories: 300,
        protein: 0,
        fats: 30,
        carbs: 0,
      },
    ],
    customDishName: "Cheese Cocoa",
  },
];
